Feat/improve copy to clipboard
out-of-cheese-error/the-way pull request #118
Opened 2022-01-09 03:41 UTC by Jarsop

Adding a new file `copy.rs` which contains the supported copy commands and the necessary facility functions to use it.
It allows to easily add a new copy command.
Add also a new field (`copy_cmd`) in the default configuration and the configuration file with a dedicated way to serialize and deserialize this field. It allows to have a default command according to the conditional compilation on the detected OS.

2022-01-09 11:42 UTC, Ninjani requested changes
Thanks! I've added some comments

2022-01-09 11:42 UTC, Ninjani commented on src/copy.rs
> +pub(crate) fn deserialize_copy_cmd<'de, D>(deserializer: D) -> Result<CopyCmd, D::Error>
I would expect the value in the configuration file to contain the entire command with arguments (e.g "xclip -in -selection clipboard"). This way people can add in their own commands.

2022-01-09 11:42 UTC, Ninjani commented on src/copy.rs
> +    #[cfg(target_os = "linux")]
Would be good to add a case where it doesn't match any of these OSes and returns an empty list

2022-01-09 11:42 UTC, Ninjani commented on src/copy.rs
> +    copy_cmds[0].to_owned()
Instead, could make this return a Result and give a message like "No default command found for detected OS. Please add a supported command to your configuration file (as copy_cmd)"

2022-01-09 11:42 UTC, Ninjani commented on tests/cli.rs
> +fn copy_shell_script_rexpect() -> rexpect::errors::Result<()> {
The copy tests are the one called `copy` and `copy_shell_script` just above this function. Please revert this change as they call out to this function to test the interactive behavior.

2022-01-09 15:14 UTC, Jarsop commented
Hello @Ninjani, does it means that you want to support only one command by OS and just override the default command by the configuration field ?

2022-01-09 17:25 UTC, Ninjani commented
Yes, that's what I had in mind, that way it's easy to swap out with xsel or wl-copy or anything the user wants. What do you think?

2022-01-09 17:35 UTC, Jarsop commented
Sounds good too, maybe a bit harder to handling the errors properly but more generic. I think an example in the `README` for that case will be welcome :) (I will add it)

2022-01-09 17:37 UTC, Jarsop commented
I think that I will also add an error kind for the case of we are on a non supported OS by default copy command

2022-01-09 21:18 UTC, Jarsop commented
I will update the `README` soon, after your review

2022-01-23 18:47 UTC, Jarsop commented
@Ninjani Any update about this topic?

2022-01-25 23:08 UTC, Jarsop commented on src/errors.rs
> +    #[error("EmptyCopyCommand: The field `copy_cmd` from configuration is empty")]
Yes, I agree! I've changed the way (no joke :smiley: ) to handle this.

2022-01-25 23:12 UTC, Jarsop commented
> Sorry got caught up with work. Looks pretty good, just a minor change and we're good to go I think.

No problem we are all busy :)

2022-01-25 23:16 UTC, Jarsop commented on src/errors.rs
> +    #[error("EmptyCopyCommand: The field `copy_cmd` from configuration is empty")]
But just to clarify the `EmptyCopyCommand` was only raised when the field is empty in the configuration file and not if the field is not present. But it's fixed.

2022-01-27 17:00 UTC, Ninjani approved these changes

2022-01-27 17:03 UTC, Ninjani commented
Looks good! Would you like to update the README and CHANGELOG?

2022-01-27 23:49 UTC, Jarsop commented
> Looks good! Would you like to update the README and CHANGELOG?

Yes I will do it ?

2022-01-28 02:02 UTC, Jarsop commented
Done. I also added an example with `xsel` and I incremented the minor version (I don't know if you consider it a patch or a minor increment)

2022-02-02 18:11 UTC, merged

2022-02-02 18:11 UTC, Ninjani commented
Thanks @Jarsop I'll make a new release this weekend